# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(585, 630)
        Window.setMinimumSize(QtCore.QSize(585, 630))
        Window.setMaximumSize(QtCore.QSize(585, 630))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(16)
        Window.setFont(font)
        Window.setStyleSheet("QMainWindow {\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.group_one = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(16)
        self.group_one.setFont(font)
        self.group_one.setTitle("")
        self.group_one.setAlignment(QtCore.Qt.AlignCenter)
        self.group_one.setObjectName("group_one")
        self.gridLayout = QtWidgets.QGridLayout(self.group_one)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_img_host = QtWidgets.QPushButton(self.group_one)
        self.btn_img_host.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.btn_img_host.setFont(font)
        self.btn_img_host.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/Cloud Storage.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Icons/Cloud Storage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_img_host.setIcon(icon)
        self.btn_img_host.setIconSize(QtCore.QSize(40, 40))
        self.btn_img_host.setFlat(True)
        self.btn_img_host.setObjectName("btn_img_host")
        self.gridLayout.addWidget(self.btn_img_host, 0, 0, 1, 1)
        self.btn_img_username = QtWidgets.QPushButton(self.group_one)
        self.btn_img_username.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.btn_img_username.setFont(font)
        self.btn_img_username.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/User Shield.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("Icons/User Shield.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_img_username.setIcon(icon1)
        self.btn_img_username.setIconSize(QtCore.QSize(40, 40))
        self.btn_img_username.setFlat(True)
        self.btn_img_username.setObjectName("btn_img_username")
        self.gridLayout.addWidget(self.btn_img_username, 0, 1, 1, 1)
        self.btn_img_password = QtWidgets.QPushButton(self.group_one)
        self.btn_img_password.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.btn_img_password.setFont(font)
        self.btn_img_password.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/Password.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("Icons/Cloud Storage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_img_password.setIcon(icon2)
        self.btn_img_password.setIconSize(QtCore.QSize(40, 40))
        self.btn_img_password.setFlat(True)
        self.btn_img_password.setObjectName("btn_img_password")
        self.gridLayout.addWidget(self.btn_img_password, 0, 2, 1, 1)
        self.input_hostname = QtWidgets.QLineEdit(self.group_one)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.input_hostname.setFont(font)
        self.input_hostname.setAlignment(QtCore.Qt.AlignCenter)
        self.input_hostname.setObjectName("input_hostname")
        self.gridLayout.addWidget(self.input_hostname, 1, 0, 1, 1)
        self.input_username = QtWidgets.QLineEdit(self.group_one)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.input_username.setFont(font)
        self.input_username.setAlignment(QtCore.Qt.AlignCenter)
        self.input_username.setObjectName("input_username")
        self.gridLayout.addWidget(self.input_username, 1, 1, 1, 1)
        self.input_password = QtWidgets.QLineEdit(self.group_one)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.input_password.setFont(font)
        self.input_password.setAlignment(QtCore.Qt.AlignCenter)
        self.input_password.setObjectName("input_password")
        self.gridLayout.addWidget(self.input_password, 1, 2, 1, 1)
        self.list_log = QtWidgets.QListWidget(self.group_one)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        self.list_log.setFont(font)
        self.list_log.setObjectName("list_log")
        self.gridLayout.addWidget(self.list_log, 2, 0, 1, 3)
        self.gridLayout_5.addWidget(self.group_one, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tab_transfers = QtWidgets.QTabWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.tab_transfers.setFont(font)
        self.tab_transfers.setObjectName("tab_transfers")
        self.tab_transfer_queue = QtWidgets.QWidget()
        self.tab_transfer_queue.setObjectName("tab_transfer_queue")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_transfer_queue)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.list_transfer = QtWidgets.QListView(self.tab_transfer_queue)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        self.list_transfer.setFont(font)
        self.list_transfer.setObjectName("list_transfer")
        self.gridLayout_3.addWidget(self.list_transfer, 0, 0, 1, 1)
        self.tab_transfers.addTab(self.tab_transfer_queue, "")
        self.tab_transfer_complete = QtWidgets.QWidget()
        self.tab_transfer_complete.setObjectName("tab_transfer_complete")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_transfer_complete)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.list_finished_transfer = QtWidgets.QListWidget(self.tab_transfer_complete)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        self.list_finished_transfer.setFont(font)
        self.list_finished_transfer.setObjectName("list_finished_transfer")
        self.gridLayout_4.addWidget(self.list_finished_transfer, 0, 0, 1, 1)
        self.tab_transfers.addTab(self.tab_transfer_complete, "")
        self.gridLayout_2.addWidget(self.tab_transfers, 0, 0, 1, 1)
        self.bar_progress = QtWidgets.QProgressBar(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.bar_progress.setFont(font)
        self.bar_progress.setProperty("value", 0)
        self.bar_progress.setTextVisible(False)
        self.bar_progress.setObjectName("bar_progress")
        self.gridLayout_2.addWidget(self.bar_progress, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Window)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Window)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.toolBar.setFont(font)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.NoToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        Window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_sync = QtWidgets.QAction(Window)
        self.action_sync.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/Download From FTP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_sync.setIcon(icon3)
        self.action_sync.setObjectName("action_sync")
        self.action_download_path = QtWidgets.QAction(Window)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/Downloads Folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_download_path.setIcon(icon4)
        self.action_download_path.setObjectName("action_download_path")
        self.action_load_settings = QtWidgets.QAction(Window)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/More.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_load_settings.setIcon(icon5)
        self.action_load_settings.setObjectName("action_load_settings")
        self.action_save_settings = QtWidgets.QAction(Window)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save_settings.setIcon(icon6)
        self.action_save_settings.setObjectName("action_save_settings")
        self.action_find_remote_folders = QtWidgets.QAction(Window)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/Find and Replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_find_remote_folders.setIcon(icon7)
        self.action_find_remote_folders.setObjectName("action_find_remote_folders")
        self.actionDownload_path = QtWidgets.QAction(Window)
        self.actionDownload_path.setObjectName("actionDownload_path")
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_download_path)
        self.toolBar.addAction(self.action_load_settings)
        self.toolBar.addAction(self.action_save_settings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_find_remote_folders)
        self.toolBar.addAction(self.action_sync)
        self.toolBar.addSeparator()

        self.retranslateUi(Window)
        self.tab_transfers.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "FTP File Sync"))
        self.tab_transfers.setTabText(self.tab_transfers.indexOf(self.tab_transfer_queue), _translate("Window", "Transfer Queue"))
        self.tab_transfers.setTabText(self.tab_transfers.indexOf(self.tab_transfer_complete), _translate("Window", "Complete Transfers"))
        self.toolBar.setWindowTitle(_translate("Window", "toolBar"))
        self.action_sync.setText(_translate("Window", "Start"))
        self.action_download_path.setText(_translate("Window", "Download Path"))
        self.action_load_settings.setText(_translate("Window", "Load Settings"))
        self.action_save_settings.setText(_translate("Window", "Save Settings"))
        self.action_find_remote_folders.setText(_translate("Window", "Find Remote Folders"))
        self.actionDownload_path.setText(_translate("Window", "Download path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())

